[package]
name = "tbd"
version = "0.3.0"
edition = "2024"

[dependencies]
#libc = "0.2.174"  #maybe use instead of nix, depends on if nix is gonna play along or not
iced = {version = "0.13.1", features = ["svg", "advanced"]}
nix = {version = "0.30.1", features = ["ptrace", "signal", "process"]}
#num_enum = "0.7.4"
iced-x86 = "1.21.0"
object = "0.37.3"
toml = "0.9.8"
rust-embed = {version = "8.8.0", features = ["include-exclude"]}