

[layout]
status_bar = true
sidebar_left = true
sidebar_right = true
panel = true
panel_mode = "middle" # "middle", "left", "right", "full"

[layout.panes]
main = ["code"] # next to each other
left = ["control", "memory"] # under each other
right = ["registers", "stack"] # under each other
panel = ["terminal"] # next to each other
